version: '3'

services:
  web:
    build: .
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
   
 
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: ny_taxi
        container_name: db
      ports:
        - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080